services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    volumes:
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    restart: always
    command: celery -A root worker -l INFO
    volumes:
      - media_data:/app/media
    env_file:
      - .env.local
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    restart: always
    command: celery -A root beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env.local
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  media_data: