# Generated by Django 5.2.8 on 2026-04-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_review_cleanliness_review_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='free_cancellation_hours',
            field=models.PositiveIntegerField(default=24, help_text='Sayohat boshlanishidan necha soat oldingacha bepul bekor qilish mumkin?'),
        ),
    ]
