# Generated by Django 5.2.8 on 2026-04-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_destination_free_cancellation_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='visited_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
