# Generated by Django 6.0.4 on 2026-04-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_user_type_user_role_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'destination')},
        ),
    ]
