# Generated by Django 6.0.4 on 2026-04-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='visible_reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visible Reviews Count'),
        ),
    ]
