# Generated by Django 6.0.4 on 2026-04-29 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_destination_visible_reviews_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(help_text='Masalan: 14:30', verbose_name='Boshlanish vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='apps.destination')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['time'],
                'unique_together': {('destination', 'time')},
            },
        ),
    ]
