# Generated by Django 6.0.4 on 2026-04-29 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('booking_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('booking_date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('guest_first_name', models.CharField(blank=True, max_length=100)),
                ('guest_last_name', models.CharField(blank=True, max_length=100)),
                ('guest_email', models.CharField(blank=True, max_length=150)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('tickets_data', models.JSONField(default=dict, help_text="Example: {'Adult': 2, 'Child': 1}")),
                ('total_guests', models.PositiveIntegerField(default=1)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='apps.destination')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_number'], name='apps_bookin_booking_d65588_idx'), models.Index(fields=['status'], name='apps_bookin_status_12875b_idx')],
            },
        ),
    ]
