# Generated by Django 6.0.4 on 2026-04-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='card_mask',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Special Requests'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('paypal', 'PayPal'), ('kaspi', 'Kaspi.kz'), ('apple_pay', 'Apple Pay')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
