# Generated by Django 6.0.4 on 2026-04-30 10:34

import apps.models.orders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_booking_card_mask_booking_card_type_booking_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default=apps.models.orders.generate_booking_number, editable=False, max_length=50, unique=True),
        ),
    ]
