# Generated by Django 6.0.4 on 2026-04-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_booking_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('paypal', 'PayPal'), ('kaspi', 'Kaspi.kz'), ('apple_pay', 'Apple Pay'), ('payme', 'Payme'), ('click', 'Click')], default='card', max_length=20),
        ),
    ]
