# Generated by Django 6.0.4 on 2026-04-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
