# Generated by Django 6.0.4 on 2026-05-02 07:42

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_review_helpful_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='apps.region'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.ForeignKey(limit_choices_to={'country__region__level': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='apps.city'),
        ),
    ]
