# Generated by Django 6.0.4 on 2026-05-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_trip_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_flash_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['city', 'is_featured'], name='apps_destin_city_id_422165_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['city', 'is_trending'], name='apps_destin_city_id_145f09_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['country'], name='apps_destin_country_6ba54f_idx'),
        ),
    ]
