# Generated by Django 6.0.4 on 2026-05-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_backfill_booking_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='notify_bookings',
            field=models.BooleanField(default=True, verbose_name='Booking Updates'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='notify_price_alerts',
            field=models.BooleanField(default=True, verbose_name='Price Alerts'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='notify_promotions',
            field=models.BooleanField(default=True, verbose_name='Promotions & Offers'),
        ),
        migrations.AddField(
            model_name='user',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('budget', 'Budget ($0-50/day)'), ('mid', 'Mid-Range ($50-150/day)'), ('luxury', 'Luxury ($150+/day)')], max_length=10, verbose_name='Budget Range'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/covers/%Y/%m/%d/', verbose_name='Cover Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.CharField(blank=True, max_length=150, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list, verbose_name='Languages Spoken'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10, verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='user',
            name='travel_styles',
            field=models.JSONField(blank=True, default=list, verbose_name='Travel Styles'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
