# Generated by Django 6.0.4 on 2026-05-22 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_notificationsetting_notify_bookings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('quiz_styles', models.CharField(blank=True, help_text='vergul bilan: cultural,beach,adventure', max_length=200)),
                ('quiz_budget', models.CharField(blank=True, help_text='budget | mid | luxury', max_length=20)),
                ('quiz_party', models.CharField(blank=True, help_text='solo | partner | family | friends', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rec_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Profile',
                'verbose_name_plural': 'Recommendation Profiles',
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('up', 'Good match'), ('down', 'Bad match'), ('dismiss', 'Not interested')], max_length=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_feedback', to='apps.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Feedback',
                'verbose_name_plural': 'Recommendation Feedback',
                'constraints': [models.UniqueConstraint(fields=('user', 'destination'), name='uniq_rec_feedback_user_dest')],
            },
        ),
    ]
