# Generated by Django 6.0.4 on 2026-05-30 09:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_recommendationprofile_recommendationfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='additional_info_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Qo'shimcha ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='additional_info_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Qo'shimcha ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='additional_info_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Qo'shimcha ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='description_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='featured_badge_en',
            field=models.CharField(blank=True, help_text='#1 Best seller in London', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='featured_badge_ru',
            field=models.CharField(blank=True, help_text='#1 Best seller in London', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='featured_badge_uz',
            field=models.CharField(blank=True, help_text='#1 Best seller in London', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='location_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='location_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='location_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='name_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='price_label_en',
            field=models.CharField(default='person', help_text='person | couple | family', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='price_label_ru',
            field=models.CharField(default='person', help_text='person | couple | family', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='price_label_uz',
            field=models.CharField(default='person', help_text='person | couple | family', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='restrictions_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Cheklovlar', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='restrictions_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Cheklovlar', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='restrictions_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Cheklovlar', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_description_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='whats_included_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Nimalar kiradi', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='whats_included_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Nimalar kiradi', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='whats_included_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Nimalar kiradi', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='why_visit_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Nima uchun tashrif buyurish kerak', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='why_visit_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Nima uchun tashrif buyurish kerak', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='why_visit_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Nima uchun tashrif buyurish kerak', null=True),
        ),
        migrations.AddField(
            model_name='destinationfaq',
            name='answer_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='destinationfaq',
            name='answer_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='destinationfaq',
            name='answer_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='destinationfaq',
            name='question_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='destinationfaq',
            name='question_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='destinationfaq',
            name='question_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='age_label_en',
            field=models.CharField(blank=True, help_text='age 16+', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='age_label_ru',
            field=models.CharField(blank=True, help_text='age 16+', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='age_label_uz',
            field=models.CharField(blank=True, help_text='age 16+', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='name_en',
            field=models.CharField(help_text='Adult (age 16+) | Child | Infant …', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='name_ru',
            field=models.CharField(help_text='Adult (age 16+) | Child | Infant …', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='name_uz',
            field=models.CharField(help_text='Adult (age 16+) | Child | Infant …', max_length=100, null=True),
        ),
    ]
